name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read
  statuses: write

# Cancel all previous runs of the same workflow when a new one is triggered in the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'tags/')}}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Remove unnecessary tools folder 🧹
        run: rm -rf /opt/hostedtoolcache

      - name: Run lint ✅
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}